name: whatsApp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  country_code_picker: ^3.3.0
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_file_dialog: ^3.0.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  page_transition: ^2.1.0
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/svg/
    - assets/fonts/
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
flutter_intl:
  enabled: true
